client/urls.py
from django.urls import path

from client.views import (
    ClientListView,
    ClientDetailView,
    ClientCreateView,
    ClientDeleteView,
    ClientUpdateView,
)

app_name = "client"

urlpatterns = [
    path("", ClientListView.as_view(), name="list"),
    path("add/", ClientCreateView.as_view(), name="add"),
    path("<int:id>/", ClientDetailView.as_view(), name="detail"),
    path("<int:id>/delete/", ClientDeleteView.as_view(), name="delete"),
    path("<int:id>/edit/", ClientUpdateView.as_view(), name="edit"),
]

core/urls.py
from django.urls import path

import core.views as views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
]

crm_core/urls.py
from django.contrib import admin
from django.urls import path, include

# !!!Only for development !!!
from django.conf import settings
from django.conf.urls.static import static

# !!!Only for development !!!

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("users/", include("userprofile.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/leads/", include("lead.urls")),
    path("dashboard/clients/", include("client.urls")),
    path("dashboard/teams/", include("team.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from dashboard.views import (
    DashboardListView,
)

app_name = "dashboard"

urlpatterns = [
    path("", DashboardListView.as_view(), name="dashboard"),
]

client/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User

from team.models import Team


class ClientQuerySet(models.QuerySet):
    def get_for_user(self, user):
        """
        Return all client records related to the given user.

        Includes:
        - clients created by the user,
        - clients assigned to teams the user is a member of,
        - clients assigned to teams created by the user.
        """
        q_created_by = Q(created_by=user)  # client created by user
        q_teams_in = Q(team__in=user.teams.all())  # client in the same team as user
        q_teams_created = Q(
            team__in=user.created_teams.all()
        )  # client in the team created by user

        query = q_created_by | q_teams_in | q_teams_created

        return self.filter(query).distinct()


class ClientManager(models.Manager):
    def get_queryset(self):
        """
        Return a ClientQuerySet instance for this manager.
        """
        return ClientQuerySet(self.model, using=self._db)

    def get_for_user(self, user):
        """
        Delegate to ClientQuerySet.get_for_user(user).
        """
        return self.get_queryset().get_for_user(user=user)


class Client(models.Model):
    """
    Database model for <b>Clients</b>. Fields:
    - team ForeignKey with Team model
    - name CharField
    - email EmailField
    - description TextField, can be blank/null
    - created_by ForeignKey with User model
    - created_at DateTimeField with auto_now_add
    - modified_at DateTimeField with auto_now
    """

    team = models.ForeignKey(
        Team,
        related_name="clients",
        on_delete=models.CASCADE,
    )
    name = models.CharField(
        max_length=255,
    )
    email = models.EmailField()
    description = models.TextField(
        blank=True,
        null=True,
    )
    created_by = models.ForeignKey(
        User,
        related_name="clients",
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    modified_at = models.DateTimeField(
        auto_now=True,
    )

    objects = ClientManager()

    def __str__(self):
        return self.name

client/forms.py
from django import forms

from client.models import (
    Client,
)
from team.models import (
    Team,
)


class ClientForm(forms.ModelForm):
    """
    Form for Client model
    """

    class Meta:
        model = Client
        fields = (
            "name",
            "email",
            "description",
            "team",
        )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        # Retrive from database only teams created by requested user.
        # If no teams was found, return none queryset
        if "team" in self.fields:
            if user is not None:
                self.fields["team"].queryset = Team.objects.filter(members=user)
            else:
                self.fields["team"].queryset = Team.objects.none()

    def clean(self):
        cleaned_data = super().clean()

        new_team = cleaned_data.get("team")

        # check if newly created instance
        if self.instance.pk:
            old_team = self.instance.team

            # if edited check if team was changed
            team_changed = old_team != new_team
            if not team_changed:
                return cleaned_data

        # if team was changed or newly created record
        # then check if client does not exceed team plan limit
        if new_team:
            client_count = Client.objects.filter(team=new_team).count()
            plan_lim = new_team.plan.max_clients

            # raise if exceeded
            if client_count >= plan_lim:
                raise forms.ValidationError(
                    f"The team plan for '{new_team.name}' was exceeded. "
                    f"It already has {client_count} of {plan_lim} clients. "
                )

        return cleaned_data

client/views.py
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)

from client.models import (
    Client,
)
from client.forms import (
    ClientForm,
)


class ClientListView(LoginRequiredMixin, ListView):
    """
    View for listing the clients created by requested user
    """

    model = Client
    template_name = "client/list_clients.html"
    context_object_name = "clients"

    # get all clients created by user
    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(created_by=self.request.user)
            .order_by("-created_at")
        )


class ClientDetailView(LoginRequiredMixin, DetailView):
    """
    View for list client details
    """

    model = Client
    pk_url_kwarg = "id"
    context_object_name = "client"
    template_name = "client/detail_client.html"

    # get clients related to request user
    def get_queryset(self):
        return super().get_queryset().get_for_user(self.request.user)


class ClientCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    View for adding a new client
    """

    model = Client
    form_class = ClientForm
    template_name = "client/client_form.html"
    success_url = reverse_lazy("client:list")

    def get_success_message(self, cleaned_data):
        return f'The client "{self.object.name}" has been created'

    def form_valid(self, form):
        # add value to created_by field and save form
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        # specify user variable for the form init
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = f"Create new client"
        context["button_name"] = "Create"
        return context


class ClientDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    """
    View for deleting a client created by requested user
    and having a certain id
    """

    model = Client
    success_url = reverse_lazy("client:list")
    pk_url_kwarg = "id"
    context_object_name = "client"

    def get_success_message(self, cleaned_data):
        return f'The client "{self.object.name}" was deleted successfully'

    def get_queryset(self):
        # get queryset created by current user
        return super().get_queryset().filter(created_by=self.request.user)


class ClientUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    View for edit client, created by requested user and
    having a certain id
    """

    model = Client
    form_class = ClientForm
    pk_url_kwarg = "id"
    template_name = "client/client_form.html"

    def get_queryset(self):
        return super().get_queryset().filter(created_by=self.request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse_lazy("client:detail", kwargs={"id": self.object.id})

    def get_success_message(self, cleaned_data):
        return f'The client "{self.object.name}" has been successfully updated.'

    def get_context_data(self, **kwargs):
        # pass additional data to client_form
        context = super().get_context_data(**kwargs)
        context["page_title"] = f'Edit "{self.object.name}"'
        context["button_name"] = "Edit"
        return context

client/templates/client/add_client.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block title %}Add Client{% endblock %}

{% block content %}

    <div class="py-6 px-6">
        <h1 class="text-center text-xl">
            Add client
        </h1>
        <div class="mt-6">
            <form method="post" action="." class="max-w-xl mx-auto">
                {% csrf_token %}

                {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 py-4 px-4 bg-red-100 border border-red-400 text-red-700 rounded-xl">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}

                        {{ form.non_field_errors }}
                    </div>
                {% endif %}

                {{ form.name|add_label_class:"mt-3" }}
                {{ form.name|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
                
                {{ form.email|add_label_class:"mt-3" }}
                {{ form.email|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
                
                {{ form.description|add_label_class:"mb-5" }}
                {{ form.description|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
                
                {{ form.team|add_label_class:"mt-3" }}
                {{ form.team|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
                    
                    
                <a href="{% url 'client:list'%}" class="py-4 px-8 mt-6 bg-gray-500 text-white rounded-xl item">Back</a>
                <button class="py-4 px-8 bg-teal-500 text-white rounded-xl mt-6">Add</button>
            </form>
        </div>
    </div>

{% endblock %}

client/templates/client/client_confirm_delete.html
{% extends 'core/base.html' %}

{% load widget_tweaks %}

{% block title %}{{ client.name }}{% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="text-center text-xl">
        Delete client
    </h1>
    <div class="mt-6">
        <form method="post", action="." class="max-w-xl mx-auto">
            {% csrf_token %}
            <p class="text-center my-2 py-4 px-6">Are you sure, you want to delete "<strong>{{ client.name }}</strong>"?</p>
            <a href="{% url 'client:detail' client.id %}" class="py-4 px-8 mt-6 bg-gray-500 text-white rounded-xl">Back</a>
            <button class="py-4 px-8 ml-4 mt-6 bg-teal-500 text-white rounded-xl">Confirm</button>
        </form>
    </div>
</div>
    
{% endblock %}

client/templates/client/client_form.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block title %}{{page_title}}{% endblock %}

{% block content %}

    <div class="py-6 px-6">
        <h1 class="text-center text-xl">
            {{page_title}}
        </h1>
        <div class="mt-6">
            <form method="post" action="." class="max-w-xl mx-auto">
                {% csrf_token %}

                {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 py-4 px-4 bg-red-100 border border-red-400 text-red-700 rounded-xl">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}

                        {{ form.non_field_errors }}
                    </div>
                {% endif %}

                {{ form.name|add_label_class:"mt-3" }}
                {{ form.name|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
                
                {{ form.email|add_label_class:"mt-3" }}
                {{ form.email|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
                
                {{ form.description|add_label_class:"mb-5" }}
                {{ form.description|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
                
                {{ form.team|add_label_class:"mt-3" }}
                {{ form.team|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
                    
                    
                <a href="{% url 'client:list'%}" class="py-4 px-8 mt-6 bg-gray-500 text-white rounded-xl item">Back</a>
                <button class="py-4 px-8 bg-teal-500 text-white rounded-xl mt-6">{{button_name}}</button>
            </form>
        </div>
    </div>

{% endblock %}

client/templates/client/detail_client.html
{% extends 'core/base.html' %}

{% block title %}{{ client.name }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{ client.name }}</h1>

        {% if client.description %}
            <div class="flex gap-4 mb-2">
                <div class="pr-1">
                    <strong>Description:</strong> 
                </div>
                <div class="w-1/2 p-4 bg-gray-100 rounded-xl border border-gray-200  ">
                    {{ client.description }}
                </div>  
            </div>
        {% endif %}
        
        <div class="flex gap-4 mb-4">
            <div class="pr-6">
                <strong>Email:</strong> 
            </div>
            <div class="flex-1 pl-7">
                {{ client.email }}
            </div>  
        </div>

        <div class="flex gap-4 mb-4">
            <div class="pr-6">
                <strong>Team:</strong> 
            </div>
            <div class="flex-1 pl-7">
                {{ client.team }}
            </div>  
        </div>

        <div class="flex gap-4 mb-4">
            <div class="pr-1">
                <strong>Created at:</strong> 
            </div>
            <div class="flex-1 pl-2">
                {{ client.created_at|date:"d M, Y H:i" }}
            </div>  
        </div>

        <div class="flex gap-4 mb-4">
            <div class="pr-1">
                <strong>Modified at:</strong> 
            </div>
            <div class="flex-1">
                {{ client.modified_at|date:"d M, Y H:i" }}
            </div>  
        </div>

        <div class="flex gap-4 mb-4">
            <div class="pr-1">
                <strong>Created by:</strong> 
            </div>
            <div class="flex-1 pl-2">
                {{ client.created_by.username }}
            </div>  
        </div>
        <div class="block inline-block mb-3 mt-6 space-x-3">
            <a href="{% url 'client:edit' client.id %}" class="px-4 py-3 bg-teal-500 rounded-xl text-white hover:bg-teal-300">Edit</a>
            <a href="{% url 'client:delete' client.id %}" class="px-4 py-3 bg-red-500 rounded-xl text-white hover:bg-red-300">Delete</a>
        </div>

        <hr class="my-4 text-gray-200 border-1">
        
        <a href="{% url 'dashboard:dashboard' %}" class="hover:text-gray-500"><-- Back to dashboard</a>
        <hr class="my-4 text-gray-200 border-1">
        <a href="{% url 'client:list' %}" class="hover:text-gray-500"><-- Back to my clients</a>
        
    </div>
{% endblock %}

client/templates/client/list_clients.html
{% extends 'core/base.html' %}

{% block title %}Clients{% endblock %}

{% block content %}
    <h1 class="mb-4 text-center text-xl">
        My Clients List 
    </h1>

    <div class="flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Date added</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Last modified</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Team</p>
    </div>
    {% for client in clients %}
        <div class="flex justify-between">
            <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %} hover:text-gray-500">
                <a href="{% url 'client:detail' client.id %}">{{ client.name }}</a>
            </p>
            <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %}">{{ client.created_at|date:"d M, Y H:i" }}</p>
            <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %}">{{ client.modified_at|date:"d M, Y H:i" }}</p>
            <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %}">
                {% if client.team %}
                    {{ client.team }}
                {% else %}
                    ---
                {% endif %}
            </p>
        </div>

    {% empty %}
        <p class="py-6">There are no clients in the database yet...</p>
    {% endfor %}

    <a href="{% url 'client:add' %}" class="block inline-block py-3 px-6 bg-teal-600 rounded-xl text-white mt-6">
        + Add client
    </a>
{% endblock %}