core/urls.py
from django.urls import path

import core.views as views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
]

crm_core/urls.py
from django.contrib import admin
from django.urls import path, include

# !!!Only for development !!!
from django.conf import settings
from django.conf.urls.static import static

# !!!Only for development !!!

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("users/", include("userprofile.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/leads/", include("lead.urls")),
    path("dashboard/clients/", include("client.urls")),
    path("dashboard/teams/", include("team.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from dashboard.views import (
    DashboardListView,
)

app_name = "dashboard"

urlpatterns = [
    path("", DashboardListView.as_view(), name="dashboard"),
]

lead/urls.py
from django.urls import path

from lead.views import (
    LeadsListView,
    LeadDetailView,
    LeadDeleteView,
    LeadUpdateView,
    LeadCreateView,
    ConvertToClientView,
)

app_name = "lead"

urlpatterns = [
    path("", LeadsListView.as_view(), name="list"),
    path("add/", LeadCreateView.as_view(), name="add"),
    path("<id>/", LeadDetailView.as_view(), name="detail"),
    path("<id>/delete/", LeadDeleteView.as_view(), name="delete"),
    path("<id>/edit/", LeadUpdateView.as_view(), name="edit"),
    path("<id>/convert/", ConvertToClientView.as_view(), name="convert"),
]

lead/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User

from team.models import Team


class LeadQuerySet(models.QuerySet):
    def get_for_user(self, user):
        """
        Return all lead records related to the given user.

        Includes:
        - leads created by the user (this covers leads with team=None created by the user),
        - leads assigned to teams the user is a member of,
        - leads assigned to teams created by the user.
        """
        q_created_by = Q(created_by=user)  # lead created by user
        q_teams_in = Q(team__in=user.teams.all())  # lead in the same team as user
        q_tems_created = Q(
            team__in=user.created_teams.all()
        )  # lead in the team created by user

        query = q_created_by | q_teams_in | q_tems_created

        return self.filter(query).distinct()


class LeadManager(models.Manager):
    def get_queryset(self):
        """
        Return a LeadQuerySet instance for this manager.
        """
        return LeadQuerySet(self.model, using=self._db)

    def get_for_user(self, user):
        """
        Delegate to LeadQuerySet.get_for_user(user).
        """
        return self.get_queryset().get_for_user(user=user)


class Lead(models.Model):
    """
    Database model for <b>Leads</b>. Fields:
        - team ForeignKey with Team model
        - name CharField
        - email EmailField
        - description TextField, can be blank/null
        - priority CharField with choices (Low/Medium/High)
        - status CharField with choices (New/Contacted/Won/Lost)
        - converted_to_client BooleanField
        - created_by ForeignKey with User model
        - created_at DateTimeField with auto_now_add
        - modified_at DateTimeField with auto_now
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"

    CHOICES_PRIORITY = (
        (LOW, "Low"),
        (MEDIUM, "Medium"),
        (HIGH, "High"),
    )

    NEW = "new"
    CONTACTED = "contacted"
    WON = "won"
    LOST = "lost"

    CHOICES_STATUS = (
        (NEW, "New"),
        (CONTACTED, "Contacted"),
        (WON, "Won"),
        (LOST, "Lost"),
    )

    objects = LeadManager()

    team = models.ForeignKey(
        Team,
        related_name="leads",
        on_delete=models.CASCADE,
    )
    name = models.CharField(
        max_length=255,
    )
    email = models.EmailField()
    description = models.TextField(
        blank=True,
        null=True,
    )
    priority = models.CharField(
        max_length=10,
        choices=CHOICES_PRIORITY,
        default=MEDIUM,
    )
    status = models.CharField(
        max_length=10,
        choices=CHOICES_STATUS,
        default=NEW,
    )
    converted_to_client = models.BooleanField(
        default=False,
    )
    created_by = models.ForeignKey(
        User,
        related_name="leads",
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    modified_at = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name

lead/forms.py
from django import forms

from lead.models import (
    Lead,
)

from team.models import (
    Team,
)


class LeadForm(forms.ModelForm):
    """
    Form for Lead model
    """

    class Meta:
        model = Lead
        fields = (
            "name",
            "email",
            "description",
            "priority",
            "status",
            "team",
        )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

        # Retrive from database only teams created by requested user.
        # If no teams was found, return none queryset
        if "team" in self.fields:
            if user is not None:
                self.fields["team"].queryset = Team.objects.filter(members=user)
            else:
                self.fields["team"].queryset = Team.objects.none()

    def clean(self):
        cleaned_data = super().clean()

        old_team = None
        new_team = cleaned_data.get("team")

        # check if instance is newly created
        # if not check if team was changed
        if self.instance.pk:
            old_team = self.instance.team

            # check if team was not changed
            team_changed = new_team != old_team
            if not team_changed:
                return cleaned_data

        # checks if new/edited lead dont exceed
        # the team plan limit
        if new_team:
            lead_counts = Lead.objects.filter(
                team=new_team, converted_to_client=False
            ).count()
            plan_lim = new_team.plan.max_leads

            # if exceed raise the form error
            if lead_counts >= plan_lim:
                raise forms.ValidationError(
                    f"The team plan for '{new_team.name}' was exceeded. "
                    f"It already has {lead_counts} of {plan_lim} leads. "
                )

        return cleaned_data

lead/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
    CreateView,
    View,
)
from lead.forms import (
    LeadForm,
)
from client.models import (
    Client,
)
from lead.models import Lead


class LeadCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    View for create new Lead instance

    <i>login required to show this page</i>
    """

    model = Lead
    template_name = "lead/lead_form.html"
    form_class = LeadForm
    success_url = reverse_lazy("lead:list")

    def get_success_message(self, cleaned_data):
        return f'The lead "{self.object.name}" have been successfully added'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Add Lead"
        context["button_name"] = "Create"
        return context

    def form_valid(self, form):
        # after the form valid check add
        # created_by value to the instance and save to db
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)


class LeadsListView(LoginRequiredMixin, ListView):
    """
    List view for list all leads created by requested user

    <i>login required to show this page</i>
    """

    model = Lead
    template_name = "lead/list_leads.html"
    context_object_name = "leads"

    # Modify default Lead.objects.all()
    def get_queryset(self):
        queryset = super().get_queryset()

        queryset = queryset.filter(
            created_by=self.request.user,
            converted_to_client=False,
        )

        return queryset.order_by("-created_at")


class LeadDetailView(LoginRequiredMixin, DetailView):
    """
    Detail view for list lead details

    <i>login required to show this page</i>
    """

    model = Lead
    pk_url_kwarg = "id"
    context_object_name = "lead"
    template_name = "lead/detail_lead.html"

    def get_queryset(self):
        # return all Lead records related to the user
        # and filter if lead was not converted to client
        # (check LeadQuerySet to more info)
        return (
            super()
            .get_queryset()
            .get_for_user(self.request.user)
            .filter(converted_to_client=False)
        )


class LeadDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    """
    View for delete lead instance

    <i>login required to show this view</i>
    """

    model = Lead
    pk_url_kwarg = "id"
    context_object_name = "lead"
    success_url = reverse_lazy("lead:list")

    def get_queryset(self):
        return super().get_queryset().filter(created_by=self.request.user)

    def get_success_message(self, cleaned_data):
        return 'The lead "%(name)s" have been successfully deleted' % {
            "name": self.object.name
        }


class LeadUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    View for edit lead created by requested user and
    having certain id
    """

    model = Lead
    form_class = LeadForm
    pk_url_kwarg = "id"
    template_name = "lead/lead_form.html"

    def get_queryset(self):

        # choose the object only from
        # leads created by requested user
        return super().get_queryset().filter(created_by=self.request.user)

    def get_success_url(self):
        return reverse_lazy("lead:detail", kwargs={"id": self.object.id})

    def get_success_message(self, cleaned_data):
        return f'The lead "{self.object.name}" has been successfully updated.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = f'Edit "{self.object.name}"'
        context["button_name"] = "Edit"
        return context

    def get_form_kwargs(self):

        # pass the user to the form
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class ConvertToClientView(
    LoginRequiredMixin, SuccessMessageMixin, SingleObjectMixin, View
):
    """
    Convert lead into the client and add it into
    the database
    """

    model = Lead
    pk_url_kwarg = "id"

    def get_queryset(self):
        # filter leads that was created by user and
        # wasn't converted yet
        return (
            super()
            .get_queryset()
            .get_for_user(self.request.user)
            .filter(converted_to_client=False)
        )

    def get_success_message(self, cleaned_data):
        return f"The lead {self.object.name} was converted into a client"

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()
        return redirect("lead:detail", id=self.object.id)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        lead = self.object

        # checks if lead convertion will not cause the
        # client limit overflow
        client_count = Client.objects.filter(team=lead.team).count()
        plan_lim = lead.team.plan.max_clients

        # if actually cause send message error
        # and get back to the detailed page
        if client_count >= plan_lim:
            messages.error(
                request,
                f"The lead {lead.name} cant be converted into the client. "
                f"Plan was exceeded: {client_count} of {plan_lim} clients",
            )
            return redirect("lead:detail", id=lead.id)

        try:
            client = Client.objects.create(
                team=lead.team,
                name=lead.name,
                email=lead.email,
                description=lead.description,
                created_by=request.user,
            )
            lead.converted_to_client = True
            lead.save()

            messages.success(
                request,
                f'Lead "{lead.name}" was successfully converted to "{client.name}" client',
            )
            return redirect("client:detail", id=client.id)
        except Exception as e:
            messages.error(request, f"An error occured during conversion: {e}")
            return redirect("lead:detail", id=lead.id)

lead/templates/lead/add_lead.html
{% extends 'core/base.html' %}

{% load widget_tweaks %}

{% block title %}Add lead{% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="text-center text-xl">
        Add lead
    </h1>
    <div class="mt-6">
        <form method="post", action="." class="max-w-xl mx-auto">
            {% csrf_token %}

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 py-4 px-4 bg-red-100 border border-red-400 text-red-700 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            {{ form.name|add_label_class:"mt-3" }}
            {{ form.name|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
            
            {{ form.email|add_label_class:"mt-3" }}
            {{ form.email|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
            
            {{ form.description|add_label_class:"mb-5" }}
            {{ form.description|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}

            {{ form.priority|add_label_class:"mt-3" }}
            {{ form.priority|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
            
            {{ form.status|add_label_class:"mt-3" }}
            {{ form.status|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
            
            {{ form.team|add_label_class:"mt-3" }}
            {{ form.team|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}

            <a href="{% url 'lead:list'%}" class="py-4 px-8 mt-6 bg-gray-500 text-white rounded-xl item">Back</a>
            <button class="py-4 px-8 bg-teal-500 text-white rounded-xl mt-6">Add</button>
        </form>
    </div>
</div>
    
{% endblock %}

lead/templates/lead/detail_lead.html
{% extends 'core/base.html' %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{ lead.name }}</h1>

        {% if lead.description %}
            <div class="flex gap-4 mb-2">
                <div class="pr-1">
                    <strong>Description:</strong> 
                </div>
                <div class="w-1/2 p-4 bg-gray-100 rounded-xl border border-gray-200  ">
                    {{ lead.description }}
                </div>  
            </div>
        {% endif %}
        
        <div class="flex gap-4 mb-4">
            <div class="pr-6">
                <strong>Email:</strong> 
            </div>
            <div class="flex-1 pl-6">
                {{ lead.email }}
            </div>  
        </div>

        <div class="flex gap-4 mb-4">
            <div class="pr-6">
                <strong>Team:</strong> 
            </div>
            <div class="flex-1 pl-7">
                {{ lead.team }}
            </div>  
        </div>


        <div class="flex gap-4 mb-4">
            <div class="pr-5">
                <strong>Priority:</strong> 
            </div>
            <div class="flex-1 pl-3">
                <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full 
                {% if lead.get_priority_display == 'Low' %} bg-green-100 text-green-800
                {% elif lead.get_priority_display == 'Medium' %} bg-yellow-100 text-yellow-800
                {% elif lead.get_priority_display == 'High' %} bg-red-100 text-red-800
                {% endif %}">
                    {{ lead.get_priority_display }}
                </span>
            </div>  
        </div>

        <div class="flex gap-4 mb-4">
            <div class="pr-5">
                <strong>Status:</strong> 
            </div>
            <div class="flex-1 pl-5">
                <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full 
                {% if lead.get_status_display == 'New' %} bg-blue-100 text-blue-800
                {% elif lead.get_status_display == 'Contacted' %} bg-yellow-100 text-yellow-800
                {% elif lead.get_status_display == 'Won' %} bg-green-100 text-green-800
                {% elif lead.get_status_display == 'Lost' %} bg-red-100 text-red-800
                {% endif %}">
                    {{ lead.get_status_display }}
                </span>
            </div>  
        </div>

        <div class="flex gap-4 mb-4">
            <div class="pr-1">
                <strong>Created at:</strong> 
            </div>
            <div class="flex-1 pl-2">
                {{ lead.created_at|date:"d M, Y H:i" }}
            </div>  
        </div>

        <div class="flex gap-4 mb-4">
            <div class="pr-1">
                <strong>Modified at:</strong> 
            </div>
            <div class="flex-1">
                {{ lead.modified_at|date:"d M, Y H:i" }}
            </div>  
        </div>

        <div class="flex gap-4 mb-4">
            <div class="pr-1">
                <strong>Created by:</strong> 
            </div>
            <div class="flex-1 pl-1">
                {{ lead.created_by.username }}
            </div>  
        </div>

        <div class="block inline-block mt-6 mb-3 space-x-3">
            {% if not lead.converted_to_client %}
                <a href="{% url 'lead:convert' lead.id %}" class="px-4 py-3 bg-blue-500 rounded-xl text-white hover:bg-blue-300">Convert to client</a>
            {% endif %}
                <a href="{% url 'lead:edit' lead.id %}" class="px-4 py-3 bg-teal-500 rounded-xl text-white hover:bg-teal-300">Edit</a>
            <a href="{% url 'lead:delete' lead.id %}" class="px-4 py-3 bg-red-500 rounded-xl text-white hover:bg-red-300">Delete</a>
        </div>

        <hr class="my-4 text-gray-200 border-1">
        
        <a href="{% url 'dashboard:dashboard' %}" class="hover:text-gray-500"><-- Back to dashboard</a>
        <hr class="my-4 text-gray-200 border-1">
        <a href="{% url 'lead:list' %}" class="hover:text-gray-500"><-- Back to leads</a>
        
    </div>
{% endblock %}

lead/templates/lead/lead_confirm_delete.html
{% extends 'core/base.html' %}

{% load widget_tweaks %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="text-center text-xl">
        Delete lead
    </h1>
    <div class="mt-6">
        <form method="post", action="." class="max-w-xl mx-auto">
            {% csrf_token %}
            <p class="text-center my-2 py-4 px-6">Are you sure, you want to delete "<strong>{{ lead.name }}</strong>"?</p>
            <a href="{% url 'lead:detail' lead.id %}" class="py-4 px-8 mt-6 bg-gray-500 text-white rounded-xl">Back</a>
            <button class="py-4 px-8 ml-4 mt-6 bg-teal-500 text-white rounded-xl">Confirm</button>
        </form>
    </div>
</div>
    
{% endblock %}

lead/templates/lead/lead_form.html
{% extends 'core/base.html' %}

{% load widget_tweaks %}

{% block title %}{{page_title}}{% endblock %}

{% block content %}
<div class="py-6 px-6">
    <h1 class="text-center text-xl">
        {{page_title}}
    </h1>
    <div class="mt-6">
        <form method="post", action="." class="max-w-xl mx-auto">
            {% csrf_token %}

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 py-4 px-4 bg-red-100 border border-red-400 text-red-700 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            {{ form.name|add_label_class:"mt-3" }}
            {{ form.name|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
            
            {{ form.email|add_label_class:"mt-3" }}
            {{ form.email|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
            
            {{ form.description|add_label_class:"mb-5" }}
            {{ form.description|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}

            {{ form.priority|add_label_class:"mt-3" }}
            {{ form.priority|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
            
            {{ form.status|add_label_class:"mt-3" }}
            {{ form.status|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}
            
            {{ form.team|add_label_class:"mt-3" }}
            {{ form.team|add_class:"block w-full my-2 py-4 px-6 bg-white border border-gray-200 rounded-xl" }}

            <a href="{% url 'lead:list'%}" class="py-4 px-8 mt-6 bg-gray-500 text-white rounded-xl item">Back</a>
            <button class="py-4 px-8 bg-teal-500 text-white rounded-xl mt-6">{{button_name}}</button>
        </form>
    </div>
</div>
    
{% endblock %}

lead/templates/lead/list_leads.html
{% extends 'core/base.html' %}

{% block title %}Leads{% endblock %}

{% block content %}
    <h1 class="mb-4 text-center text-xl">
        My Leads List 
    </h1>

    <div class="flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Team</p>
    </div>
    {% for lead in leads %}
        <div class="flex justify-between">
            <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %} hover:text-gray-500">
                <a href="{% url 'lead:detail' lead.id%}">{{ lead.name }}</a>
            </p>
            <p class="py-2 w-full {% cycle '' 'bg-gray-100' %}">
                <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full 
                {% if lead.get_priority_display == 'Low' %} bg-green-100 text-green-800
                {% elif lead.get_priority_display == 'Medium' %} bg-yellow-100 text-yellow-800
                {% elif lead.get_priority_display == 'High' %} bg-red-100 text-red-800
                {% endif %}">
                    {{lead.get_priority_display}}
                </span>
            </p>
            <p class="py-2  w-full {% cycle '' 'bg-gray-100' %}">
                <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full 
                {% if lead.get_status_display == 'New' %} bg-blue-100 text-blue-800
                {% elif lead.get_status_display == 'Contacted' %} bg-yellow-100 text-yellow-800
                {% elif lead.get_status_display == 'Won' %} bg-green-100 text-green-800
                {% elif lead.get_status_display == 'Lost' %} bg-red-100 text-red-800
                {% endif %}">
                    {{lead.get_status_display}}
                </span>
            </p>
            <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %}">
                {% if lead.team %}
                    {{ lead.team }}
                {% else %}
                    ---
                {% endif %}
            </p>
        </div>

    {% empty %}
        <p class="py-6">There are no leads in the database yet...</p>
    {% endfor %}

    <a href="{% url 'lead:add'%}" class="block inline-block py-3 px-6 bg-teal-600 rounded-xl text-white mt-6">
        + Add lead
    </a>
{% endblock %}