client/urls.py
from django.urls import path

from client.views import (
    ClientListView,
    ClientDetailView,
    ClientCreateView,
    ClientDeleteView,
    ClientUpdateView,
)

app_name = "client"

urlpatterns = [
    path("", ClientListView.as_view(), name="list"),
    path("add/", ClientCreateView.as_view(), name="add"),
    path("<int:id>/", ClientDetailView.as_view(), name="detail"),
    path("<int:id>/delete/", ClientDeleteView.as_view(), name="delete"),
    path("<int:id>/edit/", ClientUpdateView.as_view(), name="edit"),
]

core/urls.py
from django.urls import path

import core.views as views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
]

crm_core/urls.py
from django.contrib import admin
from django.urls import path, include

# !!!Only for development !!!
from django.conf import settings
from django.conf.urls.static import static

# !!!Only for development !!!

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("users/", include("userprofile.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("dashboard/leads/", include("lead.urls")),
    path("dashboard/clients/", include("client.urls")),
    path("dashboard/teams/", include("team.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from dashboard.views import (
    DashboardListView,
)

app_name = "dashboard"

urlpatterns = [
    path("", DashboardListView.as_view(), name="dashboard"),
]

lead/urls.py
from django.urls import path

from lead.views import (
    LeadsListView,
    LeadDetailView,
    LeadDeleteView,
    LeadUpdateView,
    LeadCreateView,
    ConvertToClientView,
)

app_name = "lead"

urlpatterns = [
    path("", LeadsListView.as_view(), name="list"),
    path("add/", LeadCreateView.as_view(), name="add"),
    path("<id>/", LeadDetailView.as_view(), name="detail"),
    path("<id>/delete/", LeadDeleteView.as_view(), name="delete"),
    path("<id>/edit/", LeadUpdateView.as_view(), name="edit"),
    path("<id>/convert/", ConvertToClientView.as_view(), name="convert"),
]

lead/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User

from team.models import Team


class LeadQuerySet(models.QuerySet):
    def get_for_user(self, user):
        """
        Return all lead records related to the given user.

        Includes:
        - leads created by the user (this covers leads with team=None created by the user),
        - leads assigned to teams the user is a member of,
        - leads assigned to teams created by the user.
        """
        q_created_by = Q(created_by=user)  # lead created by user
        q_teams_in = Q(team__in=user.teams.all())  # lead in the same team as user
        q_tems_created = Q(
            team__in=user.created_teams.all()
        )  # lead in the team created by user

        query = q_created_by | q_teams_in | q_tems_created

        return self.filter(query).distinct()


class LeadManager(models.Manager):
    def get_queryset(self):
        """
        Return a LeadQuerySet instance for this manager.
        """
        return LeadQuerySet(self.model, using=self._db)

    def get_for_user(self, user):
        """
        Delegate to LeadQuerySet.get_for_user(user).
        """
        return self.get_queryset().get_for_user(user=user)


class Lead(models.Model):
    """
    Database model for <b>Leads</b>. Fields:
        - team ForeignKey with Team model
        - name CharField
        - email EmailField
        - description TextField, can be blank/null
        - priority CharField with choices (Low/Medium/High)
        - status CharField with choices (New/Contacted/Won/Lost)
        - converted_to_client BooleanField
        - created_by ForeignKey with User model
        - created_at DateTimeField with auto_now_add
        - modified_at DateTimeField with auto_now
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"

    CHOICES_PRIORITY = (
        (LOW, "Low"),
        (MEDIUM, "Medium"),
        (HIGH, "High"),
    )

    NEW = "new"
    CONTACTED = "contacted"
    WON = "won"
    LOST = "lost"

    CHOICES_STATUS = (
        (NEW, "New"),
        (CONTACTED, "Contacted"),
        (WON, "Won"),
        (LOST, "Lost"),
    )

    objects = LeadManager()

    team = models.ForeignKey(
        Team,
        related_name="leads",
        on_delete=models.CASCADE,
    )
    name = models.CharField(
        max_length=255,
    )
    email = models.EmailField()
    description = models.TextField(
        blank=True,
        null=True,
    )
    priority = models.CharField(
        max_length=10,
        choices=CHOICES_PRIORITY,
        default=MEDIUM,
    )
    status = models.CharField(
        max_length=10,
        choices=CHOICES_STATUS,
        default=NEW,
    )
    converted_to_client = models.BooleanField(
        default=False,
    )
    created_by = models.ForeignKey(
        User,
        related_name="leads",
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    modified_at = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name

dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from client.models import Client
from lead.models import Lead


class DashboardListView(LoginRequiredMixin, ListView):
    """
    View for dashboard pages with all client and leads realated to the requested user
    """

    model = Lead
    template_name = "dashboard/dashboard.html"
    context_object_name = "leads"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.get_for_user(self.request.user).filter(converted_to_client=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["clients"] = Client.objects.get_for_user(self.request.user)
        return context

dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <div>
        <h1 class="mb-4 text-center text-xl">
            Dashboard
        </h1>

        <div class="flex space-x-4">
            <div class="w-1/2 px-4 py-6 bg-gray-100 rounded-xl leads">
                <h2 class="text-lg text-center mb-6">Leads I'm in</h2>
                <div class="flex justify-between">
                    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
                    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
                    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
                    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Team</p>
                </div>
                {% for lead in leads %}
                    <div class="flex justify-between">
                        <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %} hover:text-gray-500">
                            <a href="{% url 'lead:detail' lead.id%}">{{ lead.name }}</a>
                        </p>
                        <p class="py-2 w-full {% cycle '' 'bg-gray-100' %}">
                            <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full 
                            {% if lead.get_priority_display == 'Low' %} bg-green-100 text-green-800
                            {% elif lead.get_priority_display == 'Medium' %} bg-yellow-100 text-yellow-800
                            {% elif lead.get_priority_display == 'High' %} bg-red-100 text-red-800
                            {% endif %}">
                                {{lead.get_priority_display}}
                            </span>
                        </p>
                        <p class="py-2  w-full {% cycle '' 'bg-gray-100' %}">
                            <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full 
                            {% if lead.get_status_display == 'New' %} bg-blue-100 text-blue-800
                            {% elif lead.get_status_display == 'Contacted' %} bg-yellow-100 text-yellow-800
                            {% elif lead.get_status_display == 'Won' %} bg-green-100 text-green-800
                            {% elif lead.get_status_display == 'Lost' %} bg-red-100 text-red-800
                            {% endif %}">
                                {{lead.get_status_display}}
                            </span>
                        </p>
                        <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %}">
                            {% if lead.team %}
                                {{ lead.team }}
                            {% else %}
                                ---
                            {% endif %}
                        </p>
                    </div>

                {% empty %}
                    <p class="py-6">There are no leads in the database yet...</p>
                {% endfor %}
            
            </div>
            <div class="w-1/2 px-4 py-6 bg-gray-100 rounded-xl clients">
                <h2 class="text-lg text-center mb-6">Clients I'm in</h2>
                <div class="flex justify-between">
                    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
                    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Date added</p>
                    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Last modified</p>
                    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Team</p>
                </div>
                    {% for client in clients %}
                        <div class="flex justify-between">
                            <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %} hover:text-gray-500">
                                <a href="{% url 'client:detail' client.id %}">{{ client.name }}</a>
                            </p>
                            <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %}">{{ client.created_at|date:"d M, Y H:i" }}</p>
                            <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %}">{{ client.modified_at|date:"d M, Y H:i" }}</p>
                            <p class="py-2 px-2 w-full {% cycle '' 'bg-gray-100' %}">
                                {% if client.team %}
                                    {{ client.team }}
                                {% else %}
                                    ---
                                {% endif %}
                            </p>
                        </div>

                    {% empty %}
                        <p class="py-6">There are no clients in the database yet...</p>
                    {% endfor %}
            
            </div>
        </div>
    </div>
{% endblock %}